apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-arc
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
     argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.spec.namespace }}
  project: default
  source:
    path: helm-arc
    repoURL: https://github.com/squoc/arc-deploy
    targetRevision: HEAD
    helm:
      releaseName: "{{ .Values.spec.namespace }}-system"
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
    - Replace=true
    - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
